export const actions = { 
    DELETE_DIALOG_RESPPONSE : 'DELETE_DIALOG_RESPPONSE',

    RESPOND_DECISION_DIALOG: 'RESPOND_DECISION_DIALOG',

    CUSTOMISED_MODAL_RESPONSE:"CUSTOMISED_MODAL_RESPONSE",
}