export const actions = {
   FILE_MANAGER_LOADING : "FILE_MANAGER_LOADING",
   FILE_MANAGER_FAILED : "FILE_MANAGER_FAILED",

   FETCH_FOLDERS_SUCCESS: "FETCH_FOLDERS_SUCCESS",
   CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
   UPDATE_FOLDER_SUCCESS: "UPDATE_FOLDER_SUCCESS",
   DELETE_FOLDER_SUCCESS: "DELETE_FOLDER_SUCCESS",

   FETCH_FILES_SUCCESS: "FETCH_FILES_SUCCESS",
   CREATE_FILE_SUCCESS: "CREATE_FILE_SUCCESS",
   UPDATE_FILE_SUCCESS: "UPDATE_FILE_SUCCESS",
   DOWNLOAD_FILE_SUCCESS: "DOWNLOAD_FILE_SUCCESS",
   DELETE_FILE_SUCCESS: "DELETE_FILE_SUCCESS",

   FETCH_FILE_TYPE_SUCCESS: "FETCH_FILE_TYPE_SUCCESS",
   FETCH_FILE_BY_FOLDERID_SUCCESS: "FETCH_FILE_BY_FOLDERID_SUCCESS",
   FETCH_FILE_BY_FILEID_SUCCESS: "FETCH_FILE_BY_FILEID_SUCCESS",
}