export const actions = {
FETCH_PRODUCTS_LOADING : "FETCH_PRODUCTS_LOADING",
FETCH_PRODUCTS_SUCCESS : "FETCH_PRODUCTS_SUCCESS",
FETCH_PRODUCTS_FAILED :  "FETCH_PRODUCTS_FAILED",

FETCH_USER_PRODUCTS_LOADING : "FETCH_USER_PRODUCTS_LOADING",
FETCH_USER_PRODUCTS_SUCCESS : "FETCH_USER_PRODUCTS_SUCCESS",
FETCH_USER_PRODUCTS_FAILED :  "FETCH_USER_PRODUCTS_FAILED",
}