export const actions = {
FETCH_PRODUCTS_LOADING : "FETCH_PRODUCTS_LOADING",
FETCH_PRODUCTS_SUCCESS : "FETCH_PRODUCTS_SUCCESS",
FETCH_PRODUCTS_FAILED :  "FETCH_PRODUCTS_FAILED",

FETCH_SINGLE_PRODUCT_LOADING : "FETCH_SINGLE_PRODUCT_LOADING",
FETCH_SINGLE_PRODUCT_SUCCESS : "FETCH_SINGLE_PRODUCT_SUCCESS",
FETCH_SINGLE_PRODUCT_FAILED :  "FETCH_SINGLE_PRODUCT_FAILED",

FETCH_USER_PRODUCTS_LOADING : "FETCH_USER_PRODUCTS_LOADING",
FETCH_USER_PRODUCTS_SUCCESS : "FETCH_USER_PRODUCTS_SUCCESS",
FETCH_USER_PRODUCTS_FAILED :  "FETCH_USER_PRODUCTS_FAILED",

FETCH_SINGLE_USER_PRODUCT_LOADING : "FETCH_SINGLE_USER_PRODUCT_LOADING",
FETCH_SINGLE_USER_PRODUCT_SUCCESS : "FETCH_SINGLE_USER_PRODUCT_SUCCESS",
FETCH_SINGLE_USER_PRODUCT_FAILED :  "FETCH_SINGLE_USER_PRODUCT_FAILED",


}